### 데이터 구하기
1. 서울시 자치구 년도별 cctv 현황
2. 서울시 주민등록인구 (구별) 통계

* 1번: cctv_in_seoul20220802.csv 파일을 읽어서 cctv데이터프레임에 저장하시오

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Apple SD Gothic Neo'
plt.rcParams['font.size'] = 14

In [4]:
cctv = pd.read_csv('cctv_in_seoul20220802.csv',skiprows=1,encoding='ms949')

In [6]:
cctv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   구분        26 non-null     object
 1   총계        26 non-null     object
 2   2012년 이전  26 non-null     object
 3   2012년     25 non-null     object
 4   2013년     25 non-null     object
 5   2014년     26 non-null     object
 6   2015년     26 non-null     object
 7   2016년     26 non-null     object
 8   2017년     26 non-null     object
 9   2018년     26 non-null     object
 10  2019년     26 non-null     object
 11  2020년     26 non-null     object
 12  2021년     26 non-null     object
dtypes: object(13)
memory usage: 2.8+ KB

In [7]:
cctv

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,계,"83,557","4,812","1,851","3,434","4,295","6,840","8,708","11,572","10,627","12,267","11,247","7,904"
1,종로구,"1,715",815,NaN,NaN,195,150,0,261,85,9,200,0
2,중 구,"2,447",16,114,87,77,236,240,372,386,155,361,403
3,용산구,"2,611",34,71,234,125,221,298,351,125,307,617,228
4,성동구,"3,829",163,144,208,107,325,255,967,415,490,472,283
5,광진구,"3,211",35,57,100,187,98,52,675,465,712,175,655
6,동대문구,"2,628",4,0,14,16,115,804,814,201,218,223,219
7,중랑구,"3,737",346,21,253,72,132,155,153,174,1049,934,448
8,성북구,"4,602",81,78,170,229,322,594,890,867,714,253,404
9,강북구,"3,090",8,0,22,61,124,251,29,391,1078,656,470
10,도봉구,"1,930",128,22,2,145,172,123,129,222,210,184,593
11,노원구,"2,492",0,87,164,77,514,331,175,216,320,387,221
12,은평구,"4,131",14,3,44,332,329,555,403,635,1057,288,471
13,서대문구,"3,055",730,253,155,108,137,223,356,237,343,397,116
14,마포구,"2,496",23,19,40,112,185,478,365,373,494,299,108
15,양천구,"3,650",71,174,158,134,246,424,577,837,312,346,371
16,강서구,"2,744",54,122,104,202,199,168,506,259,457,356,317
17,구로구,"4,608",852,216,349,187,268,326,540,488,434,415,533
18,금천구,"2,411",0,0,174,80,361,133,196,539,367,513,48
19,영등포구,"4,056",572,136,238,123,209,248,311,658,65,1213,283
20,동작구,"2,306",41,24,25,503,128,253,271,300,322,419,20
21,관악구,"5,149",440,84,431,439,609,622,688,674,595,331,236
22,서초구,"4,082",8,73,79,70,562,504,1041,417,339,433,556
23,강남구,"6,871",69,67,66,580,830,1293,988,745,791,926,516
24,송파구,"2,897",40,59,90,85,214,176,241,541,1073,235,143
25,강동구,"2,809",268,27,227,49,154,202,273,377,356,614,262

In [8]:
cctv = pd.read_csv('cctv_in_seoul20220802.csv',skiprows=1,encoding='ms949',thousands=',')#천단위 문자 구분

In [9]:
cctv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   구분        26 non-null     object
 1   총계        26 non-null     int64
 2   2012년 이전  26 non-null     int64
 3   2012년     25 non-null     float64
 4   2013년     25 non-null     float64
 5   2014년     26 non-null     int64
 6   2015년     26 non-null     int64
 7   2016년     26 non-null     int64
 8   2017년     26 non-null     int64
 9   2018년     26 non-null     int64
 10  2019년     26 non-null     int64
 11  2020년     26 non-null     int64
 12  2021년     26 non-null     int64
dtypes: float64(2), int64(10), object(1)
memory usage: 2.8+ KB

* 2번 : cctv에서 0번 행(계)을 삭제

In [10]:
cctv.drop(0, inplace=True)

In [11]:
cctv

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
1,종로구,1715,815,NaN,NaN,195,150,0,261,85,9,200,0
2,중 구,2447,16,114.0,87.0,77,236,240,372,386,155,361,403
3,용산구,2611,34,71.0,234.0,125,221,298,351,125,307,617,228
4,성동구,3829,163,144.0,208.0,107,325,255,967,415,490,472,283
5,광진구,3211,35,57.0,100.0,187,98,52,675,465,712,175,655
6,동대문구,2628,4,0.0,14.0,16,115,804,814,201,218,223,219
7,중랑구,3737,346,21.0,253.0,72,132,155,153,174,1049,934,448
8,성북구,4602,81,78.0,170.0,229,322,594,890,867,714,253,404
9,강북구,3090,8,0.0,22.0,61,124,251,29,391,1078,656,470
10,도봉구,1930,128,22.0,2.0,145,172,123,129,222,210,184,593
11,노원구,2492,0,87.0,164.0,77,514,331,175,216,320,387,221
12,은평구,4131,14,3.0,44.0,332,329,555,403,635,1057,288,471
13,서대문구,3055,730,253.0,155.0,108,137,223,356,237,343,397,116
14,마포구,2496,23,19.0,40.0,112,185,478,365,373,494,299,108
15,양천구,3650,71,174.0,158.0,134,246,424,577,837,312,346,371
16,강서구,2744,54,122.0,104.0,202,199,168,506,259,457,356,317
17,구로구,4608,852,216.0,349.0,187,268,326,540,488,434,415,533
18,금천구,2411,0,0.0,174.0,80,361,133,196,539,367,513,48
19,영등포구,4056,572,136.0,238.0,123,209,248,311,658,65,1213,283
20,동작구,2306,41,24.0,25.0,503,128,253,271,300,322,419,20
21,관악구,5149,440,84.0,431.0,439,609,622,688,674,595,331,236
22,서초구,4082,8,73.0,79.0,70,562,504,1041,417,339,433,556
23,강남구,6871,69,67.0,66.0,580,830,1293,988,745,791,926,516
24,송파구,2897,40,59.0,90.0,85,214,176,241,541,1073,235,143
25,강동구,2809,268,27.0,227.0,49,154,202,273,377,356,614,262

* 3번 : pop_in_seoul20220802.txt을 읽어서 pop데이터프레임에 저장

In [12]:
pop = pd.read_table('pop_in_seoul20220802.txt', skiprows=2, thousands=',') #read_table은 탭으로 구분
#pot = pd.read_csv('pop_in_seoul20220802.txt', sep='\t', skiprows=2, thousands=',')

In [13]:
pop

,기간,자치구,세대,계,남자,여자,계.1,남자.1,여자.1,계.2,남자.2,여자.2,세대당인구,65세이상고령자
0,2022.1/4,합계,4451444,9732617,4716704,5015913,9506778,4613910,4892868,225839,102794,123045,2.14,1628980
1,2022.1/4,종로구,73766,153684,74018,79666,144275,69911,74364,9409,4107,5302,1.96,28064
2,2022.1/4,중구,63767,131450,63869,67581,122173,59448,62725,9277,4421,4856,1.92,24742
3,2022.1/4,용산구,111207,236518,114571,121947,222169,106735,115434,14349,7836,6513,2.00,39461
4,2022.1/4,성동구,134533,291609,141662,149947,285073,138847,146226,6536,2815,3721,2.12,46896
5,2022.1/4,광진구,169483,353110,169525,183585,340707,164346,176361,12403,5179,7224,2.01,52604
6,2022.1/4,동대문구,169695,352592,172318,180274,337982,166823,171159,14610,5495,9115,1.99,62963
7,2022.1/4,중랑구,187693,393600,193623,199977,389043,191835,197208,4557,1788,2769,2.07,72851
8,2022.1/4,성북구,197296,442680,212277,230403,433150,208691,224459,9530,3586,5944,2.20,75719
9,2022.1/4,강북구,144725,300824,145934,154890,297384,144643,152741,3440,1291,2149,2.05,64961
10,2022.1/4,도봉구,138836,318100,154440,163660,316098,153716,162382,2002,724,1278,2.28,65122
11,2022.1/4,노원구,219065,514445,247417,267028,510486,245663,264823,3959,1754,2205,2.33,89426
12,2022.1/4,은평구,215178,476013,227172,248841,472259,225640,246619,3754,1532,2222,2.19,88418
13,2022.1/4,서대문구,145044,317075,149805,167270,305866,145958,159908,11209,3847,7362,2.11,55012
14,2022.1/4,마포구,180702,378629,176886,201743,368331,173073,195258,10298,3813,6485,2.04,55168
15,2022.1/4,양천구,181765,449378,219882,229496,446182,218554,227628,3196,1328,1868,2.45,69953
16,2022.1/4,강서구,272572,578426,277797,300629,573046,275422,297624,5380,2375,3005,2.10,93924
17,2022.1/4,구로구,181916,419984,208027,211957,396017,195002,201015,23967,13025,10942,2.18,73864
18,2022.1/4,금천구,118697,244901,123959,120942,231098,116568,114530,13803,7391,6412,1.95,41819
19,2022.1/4,영등포구,188193,400241,198080,202161,376740,185696,191044,23501,12384,11117,2.00,63547
20,2022.1/4,동작구,186419,394649,190377,204272,386017,186648,199369,8632,3729,4903,2.07,67470
21,2022.1/4,관악구,279353,500336,250450,249886,486375,244409,241966,13961,6041,7920,1.74,80686
22,2022.1/4,서초구,169895,413677,197665,216012,409823,195806,214017,3854,1859,1995,2.41,61404
23,2022.1/4,강남구,234612,537338,257096,280242,532577,254866,277711,4761,2230,2531,2.27,79575
24,2022.1/4,송파구,285106,668261,321963,346298,662607,319407,343200,5654,2556,3098,2.32,99854
25,2022.1/4,강동구,201926,465097,227891,237206,461300,226203,235097,3797,1688,2109,2.28,75477

In [15]:
pop[['자치구', '계.1', '65세이상고령자']]

     자치구      계.1  65세이상고령자
0     합계  9506778   1628980
1    종로구   144275     28064
2     중구   122173     24742
3    용산구   222169     39461
4    성동구   285073     46896
5    광진구   340707     52604
6   동대문구   337982     62963
7    중랑구   389043     72851
8    성북구   433150     75719
9    강북구   297384     64961
10   도봉구   316098     65122
11   노원구   510486     89426
12   은평구   472259     88418
13  서대문구   305866     55012
14   마포구   368331     55168
15   양천구   446182     69953
16   강서구   573046     93924
17   구로구   396017     73864
18   금천구   231098     41819
19  영등포구   376740     63547
20   동작구   386017     67470
21   관악구   486375     80686
22   서초구   409823     61404
23   강남구   532577     79575
24   송파구   662607     99854
25   강동구   461300     75477

In [16]:
pop = pd.read_csv('pop_in_seoul20220802.txt', sep='\t', skiprows=2, thousands=',',
                  usecols=['자치구','계','계.1','계.2','65세이상고령자'])
pop

     자치구        계      계.1     계.2  65세이상고령자
0     합계  9732617  9506778  225839   1628980
1    종로구   153684   144275    9409     28064
2     중구   131450   122173    9277     24742
3    용산구   236518   222169   14349     39461
4    성동구   291609   285073    6536     46896
5    광진구   353110   340707   12403     52604
6   동대문구   352592   337982   14610     62963
7    중랑구   393600   389043    4557     72851
8    성북구   442680   433150    9530     75719
9    강북구   300824   297384    3440     64961
10   도봉구   318100   316098    2002     65122
11   노원구   514445   510486    3959     89426
12   은평구   476013   472259    3754     88418
13  서대문구   317075   305866   11209     55012
14   마포구   378629   368331   10298     55168
15   양천구   449378   446182    3196     69953
16   강서구   578426   573046    5380     93924
17   구로구   419984   396017   23967     73864
18   금천구   244901   231098   13803     41819
19  영등포구   400241   376740   23501     63547
20   동작구   394649   386017    8632     67470
21   관악구   500336   486375   13961     80686
22   서초구   413677   409823    3854     61404
23   강남구   537338   532577    4761     79575
24   송파구   668261   662607    5654     99854
25   강동구   465097   461300    3797     75477

* 4번 : pop의 칼럼 인덱스를 구별, 인구수, 한국인, 외국인, 고령자 로 변경

In [17]:
pop.columns=['구별', '인구수', '한국인', '외국인', '고령자']

In [18]:
pop.head()

    구별      인구수      한국인     외국인      고령자
0   합계  9732617  9506778  225839  1628980
1  종로구   153684   144275    9409    28064
2   중구   131450   122173    9277    24742
3  용산구   236518   222169   14349    39461
4  성동구   291609   285073    6536    46896

In [19]:
pop.drop(0, inplace=True)

In [20]:
pop.head(2)

    구별     인구수     한국인   외국인    고령자
1  종로구  153684  144275  9409  28064
2   중구  131450  122173  9277  24742

* 5번 : cctv데이터에서 '총계'로 내림차순 정렬

In [21]:
cctv.sort_values('총계', ascending=False)

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
23,강남구,6871,69,67.0,66.0,580,830,1293,988,745,791,926,516
21,관악구,5149,440,84.0,431.0,439,609,622,688,674,595,331,236
17,구로구,4608,852,216.0,349.0,187,268,326,540,488,434,415,533
8,성북구,4602,81,78.0,170.0,229,322,594,890,867,714,253,404
12,은평구,4131,14,3.0,44.0,332,329,555,403,635,1057,288,471
22,서초구,4082,8,73.0,79.0,70,562,504,1041,417,339,433,556
19,영등포구,4056,572,136.0,238.0,123,209,248,311,658,65,1213,283
4,성동구,3829,163,144.0,208.0,107,325,255,967,415,490,472,283
7,중랑구,3737,346,21.0,253.0,72,132,155,153,174,1049,934,448
15,양천구,3650,71,174.0,158.0,134,246,424,577,837,312,346,371
5,광진구,3211,35,57.0,100.0,187,98,52,675,465,712,175,655
9,강북구,3090,8,0.0,22.0,61,124,251,29,391,1078,656,470
13,서대문구,3055,730,253.0,155.0,108,137,223,356,237,343,397,116
24,송파구,2897,40,59.0,90.0,85,214,176,241,541,1073,235,143
25,강동구,2809,268,27.0,227.0,49,154,202,273,377,356,614,262
16,강서구,2744,54,122.0,104.0,202,199,168,506,259,457,356,317
6,동대문구,2628,4,0.0,14.0,16,115,804,814,201,218,223,219
3,용산구,2611,34,71.0,234.0,125,221,298,351,125,307,617,228
14,마포구,2496,23,19.0,40.0,112,185,478,365,373,494,299,108
11,노원구,2492,0,87.0,164.0,77,514,331,175,216,320,387,221
2,중 구,2447,16,114.0,87.0,77,236,240,372,386,155,361,403
18,금천구,2411,0,0.0,174.0,80,361,133,196,539,367,513,48
20,동작구,2306,41,24.0,25.0,503,128,253,271,300,322,419,20
10,도봉구,1930,128,22.0,2.0,145,172,123,129,222,210,184,593
1,종로구,1715,815,NaN,NaN,195,150,0,261,85,9,200,0

* 6번 : cctv 최근 증가율
    (2021 cctv증가수 + 2020 cctv증가수) / (2019 cctv) => 최근증가율 칼럼

In [22]:
cctv['최근증가율'] = (cctv['2021년']+cctv['2020년'])/cctv['2019년']

In [23]:
cctv

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율
1,종로구,1715,815,NaN,NaN,195,150,0,261,85,9,200,0,22.222222
2,중 구,2447,16,114.0,87.0,77,236,240,372,386,155,361,403,4.929032
3,용산구,2611,34,71.0,234.0,125,221,298,351,125,307,617,228,2.752443
4,성동구,3829,163,144.0,208.0,107,325,255,967,415,490,472,283,1.540816
5,광진구,3211,35,57.0,100.0,187,98,52,675,465,712,175,655,1.165730
6,동대문구,2628,4,0.0,14.0,16,115,804,814,201,218,223,219,2.027523
7,중랑구,3737,346,21.0,253.0,72,132,155,153,174,1049,934,448,1.317445
8,성북구,4602,81,78.0,170.0,229,322,594,890,867,714,253,404,0.920168
9,강북구,3090,8,0.0,22.0,61,124,251,29,391,1078,656,470,1.044527
10,도봉구,1930,128,22.0,2.0,145,172,123,129,222,210,184,593,3.700000
11,노원구,2492,0,87.0,164.0,77,514,331,175,216,320,387,221,1.900000
12,은평구,4131,14,3.0,44.0,332,329,555,403,635,1057,288,471,0.718070
13,서대문구,3055,730,253.0,155.0,108,137,223,356,237,343,397,116,1.495627
14,마포구,2496,23,19.0,40.0,112,185,478,365,373,494,299,108,0.823887
15,양천구,3650,71,174.0,158.0,134,246,424,577,837,312,346,371,2.298077
16,강서구,2744,54,122.0,104.0,202,199,168,506,259,457,356,317,1.472648
17,구로구,4608,852,216.0,349.0,187,268,326,540,488,434,415,533,2.184332
18,금천구,2411,0,0.0,174.0,80,361,133,196,539,367,513,48,1.528610
19,영등포구,4056,572,136.0,238.0,123,209,248,311,658,65,1213,283,23.015385
20,동작구,2306,41,24.0,25.0,503,128,253,271,300,322,419,20,1.363354
21,관악구,5149,440,84.0,431.0,439,609,622,688,674,595,331,236,0.952941
22,서초구,4082,8,73.0,79.0,70,562,504,1041,417,339,433,556,2.917404
23,강남구,6871,69,67.0,66.0,580,830,1293,988,745,791,926,516,1.823009
24,송파구,2897,40,59.0,90.0,85,214,176,241,541,1073,235,143,0.352283
25,강동구,2809,268,27.0,227.0,49,154,202,273,377,356,614,262,2.460674

* 7번 : pop에 외국인비율, 고령자비율 추가 

    외국인비율 = 외국인/인구수100     
    고령자비율 = 고령자/인구수100

In [24]:
pop['외국인비율'] = pop['외국인']/pop['인구수']*100
pop['고령자비율'] = pop['고령자']/pop['인구수']*100

In [25]:
pop.head(3)

    구별     인구수     한국인    외국인    고령자     외국인비율      고령자비율
1  종로구  153684  144275   9409  28064  6.122303  18.260847
2   중구  131450  122173   9277  24742  7.057436  18.822366
3  용산구  236518  222169  14349  39461  6.066769  16.684142

In [26]:
cctv.head(3)

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율
1,종로구,1715,815,NaN,NaN,195,150,0,261,85,9,200,0,22.222222
2,중 구,2447,16,114.0,87.0,77,236,240,372,386,155,361,403,4.929032
3,용산구,2611,34,71.0,234.0,125,221,298,351,125,307,617,228,2.752443

* 8번 : cctv의 구분을 구별로 변경

In [28]:
cctv.rename(columns={'구분':'구별'}, inplace=True)

In [29]:
cctv.head(2)

,구별,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율
1,종로구,1715,815,NaN,NaN,195,150,0,261,85,9,200,0,22.222222
2,중 구,2447,16,114.0,87.0,77,236,240,372,386,155,361,403,4.929032

* 9번 : cctv와 pop을 구별을 기준으로 병합해서 data_result에 저장.

In [30]:
data_result = pd.merge(cctv,pop,on='구별')

In [31]:
data_result

,구별,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율,인구수,한국인,외국인,고령자,외국인비율,고령자비율
0,종로구,1715,815,NaN,NaN,195,150,0,261,85,9,200,0,22.222222,153684,144275,9409,28064,6.122303,18.260847
1,용산구,2611,34,71.0,234.0,125,221,298,351,125,307,617,228,2.752443,236518,222169,14349,39461,6.066769,16.684142
2,성동구,3829,163,144.0,208.0,107,325,255,967,415,490,472,283,1.540816,291609,285073,6536,46896,2.241357,16.081808
3,광진구,3211,35,57.0,100.0,187,98,52,675,465,712,175,655,1.165730,353110,340707,12403,52604,3.512503,14.897341
4,동대문구,2628,4,0.0,14.0,16,115,804,814,201,218,223,219,2.027523,352592,337982,14610,62963,4.143599,17.857183
5,중랑구,3737,346,21.0,253.0,72,132,155,153,174,1049,934,448,1.317445,393600,389043,4557,72851,1.157774,18.508892
6,성북구,4602,81,78.0,170.0,229,322,594,890,867,714,253,404,0.920168,442680,433150,9530,75719,2.152797,17.104681
7,강북구,3090,8,0.0,22.0,61,124,251,29,391,1078,656,470,1.044527,300824,297384,3440,64961,1.143526,21.594354
8,도봉구,1930,128,22.0,2.0,145,172,123,129,222,210,184,593,3.700000,318100,316098,2002,65122,0.629362,20.472179
9,노원구,2492,0,87.0,164.0,77,514,331,175,216,320,387,221,1.900000,514445,510486,3959,89426,0.769567,17.383005
10,은평구,4131,14,3.0,44.0,332,329,555,403,635,1057,288,471,0.718070,476013,472259,3754,88418,0.788634,18.574703
11,서대문구,3055,730,253.0,155.0,108,137,223,356,237,343,397,116,1.495627,317075,305866,11209,55012,3.535126,17.349838
12,마포구,2496,23,19.0,40.0,112,185,478,365,373,494,299,108,0.823887,378629,368331,10298,55168,2.719813,14.570463
13,양천구,3650,71,174.0,158.0,134,246,424,577,837,312,346,371,2.298077,449378,446182,3196,69953,0.711205,15.566628
14,강서구,2744,54,122.0,104.0,202,199,168,506,259,457,356,317,1.472648,578426,573046,5380,93924,0.930110,16.237859
15,구로구,4608,852,216.0,349.0,187,268,326,540,488,434,415,533,2.184332,419984,396017,23967,73864,5.706646,17.587337
16,금천구,2411,0,0.0,174.0,80,361,133,196,539,367,513,48,1.528610,244901,231098,13803,41819,5.636155,17.075880
17,영등포구,4056,572,136.0,238.0,123,209,248,311,658,65,1213,283,23.015385,400241,376740,23501,63547,5.871712,15.877184
18,동작구,2306,41,24.0,25.0,503,128,253,271,300,322,419,20,1.363354,394649,386017,8632,67470,2.187260,17.096204
19,관악구,5149,440,84.0,431.0,439,609,622,688,674,595,331,236,0.952941,500336,486375,13961,80686,2.790325,16.126363
20,서초구,4082,8,73.0,79.0,70,562,504,1041,417,339,433,556,2.917404,413677,409823,3854,61404,0.931645,14.843465
21,강남구,6871,69,67.0,66.0,580,830,1293,988,745,791,926,516,1.823009,537338,532577,4761,79575,0.886034,14.809115
22,송파구,2897,40,59.0,90.0,85,214,176,241,541,1073,235,143,0.352283,668261,662607,5654,99854,0.846077,14.942365
23,강동구,2809,268,27.0,227.0,49,154,202,273,377,356,614,262,2.460674,465097,461300,3797,75477,0.816389,16.228228

In [32]:
data_result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24 entries, 0 to 23
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   구별        24 non-null     object
 1   총계        24 non-null     int64
 2   2012년 이전  24 non-null     int64
 3   2012년     23 non-null     float64
 4   2013년     23 non-null     float64
 5   2014년     24 non-null     int64
 6   2015년     24 non-null     int64
 7   2016년     24 non-null     int64
 8   2017년     24 non-null     int64
 9   2018년     24 non-null     int64
 10  2019년     24 non-null     int64
 11  2020년     24 non-null     int64
 12  2021년     24 non-null     int64
 13  최근증가율     24 non-null     float64
 14  인구수       24 non-null     int64
 15  한국인       24 non-null     int64
 16  외국인       24 non-null     int64
 17  고령자       24 non-null     int64
 18  외국인비율     24 non-null     float64
 19  고령자비율     24 non-null     float64
dtypes: float64(5), int64(14), object(1)
memory usage: 3.9+ KB

In [33]:
cctv['구별']

1      종로구
2      중 구
3      용산구
4      성동구
5      광진구
6     동대문구
7      중랑구
8      성북구
9      강북구
10     도봉구
11     노원구
12     은평구
13    서대문구
14     마포구
15     양천구
16     강서구
17     구로구
18     금천구
19    영등포구
20     동작구
21     관악구
22     서초구
23     강남구
24     송파구
25     강동구
Name: 구별, dtype: object

In [34]:
pop['구별']

1      종로구
2       중구
3      용산구
4      성동구
5      광진구
6     동대문구
7      중랑구
8      성북구
9      강북구
10     도봉구
11     노원구
12     은평구
13    서대문구
14     마포구
15     양천구
16     강서구
17     구로구
18     금천구
19    영등포구
20     동작구
21     관악구
22     서초구
23     강남구
24     송파구
25     강동구
Name: 구별, dtype: object

* 10번 : cctv의 중 구 를 중구로 변경

In [35]:
cctv.iloc[1,0] = '중구'

In [36]:
cctv

,구별,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율
1,종로구,1715,815,NaN,NaN,195,150,0,261,85,9,200,0,22.222222
2,중구,2447,16,114.0,87.0,77,236,240,372,386,155,361,403,4.929032
3,용산구,2611,34,71.0,234.0,125,221,298,351,125,307,617,228,2.752443
4,성동구,3829,163,144.0,208.0,107,325,255,967,415,490,472,283,1.540816
5,광진구,3211,35,57.0,100.0,187,98,52,675,465,712,175,655,1.165730
6,동대문구,2628,4,0.0,14.0,16,115,804,814,201,218,223,219,2.027523
7,중랑구,3737,346,21.0,253.0,72,132,155,153,174,1049,934,448,1.317445
8,성북구,4602,81,78.0,170.0,229,322,594,890,867,714,253,404,0.920168
9,강북구,3090,8,0.0,22.0,61,124,251,29,391,1078,656,470,1.044527
10,도봉구,1930,128,22.0,2.0,145,172,123,129,222,210,184,593,3.700000
11,노원구,2492,0,87.0,164.0,77,514,331,175,216,320,387,221,1.900000
12,은평구,4131,14,3.0,44.0,332,329,555,403,635,1057,288,471,0.718070
13,서대문구,3055,730,253.0,155.0,108,137,223,356,237,343,397,116,1.495627
14,마포구,2496,23,19.0,40.0,112,185,478,365,373,494,299,108,0.823887
15,양천구,3650,71,174.0,158.0,134,246,424,577,837,312,346,371,2.298077
16,강서구,2744,54,122.0,104.0,202,199,168,506,259,457,356,317,1.472648
17,구로구,4608,852,216.0,349.0,187,268,326,540,488,434,415,533,2.184332
18,금천구,2411,0,0.0,174.0,80,361,133,196,539,367,513,48,1.528610
19,영등포구,4056,572,136.0,238.0,123,209,248,311,658,65,1213,283,23.015385
20,동작구,2306,41,24.0,25.0,503,128,253,271,300,322,419,20,1.363354
21,관악구,5149,440,84.0,431.0,439,609,622,688,674,595,331,236,0.952941
22,서초구,4082,8,73.0,79.0,70,562,504,1041,417,339,433,556,2.917404
23,강남구,6871,69,67.0,66.0,580,830,1293,988,745,791,926,516,1.823009
24,송파구,2897,40,59.0,90.0,85,214,176,241,541,1073,235,143,0.352283
25,강동구,2809,268,27.0,227.0,49,154,202,273,377,356,614,262,2.460674

* 11번 : cctv, pop병합 단, cctv 총계, 최근증가율만 가져와서 병합

In [37]:
data_result = pd.merge(cctv[['구별','총계','최근증가율']],pop,on='구별')

In [38]:
data_result

      구별    총계      최근증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율
0    종로구  1715  22.222222  153684  144275   9409  28064  6.122303  18.260847
1     중구  2447   4.929032  131450  122173   9277  24742  7.057436  18.822366
2    용산구  2611   2.752443  236518  222169  14349  39461  6.066769  16.684142
3    성동구  3829   1.540816  291609  285073   6536  46896  2.241357  16.081808
4    광진구  3211   1.165730  353110  340707  12403  52604  3.512503  14.897341
5   동대문구  2628   2.027523  352592  337982  14610  62963  4.143599  17.857183
6    중랑구  3737   1.317445  393600  389043   4557  72851  1.157774  18.508892
7    성북구  4602   0.920168  442680  433150   9530  75719  2.152797  17.104681
8    강북구  3090   1.044527  300824  297384   3440  64961  1.143526  21.594354
9    도봉구  1930   3.700000  318100  316098   2002  65122  0.629362  20.472179
10   노원구  2492   1.900000  514445  510486   3959  89426  0.769567  17.383005
11   은평구  4131   0.718070  476013  472259   3754  88418  0.788634  18.574703
12  서대문구  3055   1.495627  317075  305866  11209  55012  3.535126  17.349838
13   마포구  2496   0.823887  378629  368331  10298  55168  2.719813  14.570463
14   양천구  3650   2.298077  449378  446182   3196  69953  0.711205  15.566628
15   강서구  2744   1.472648  578426  573046   5380  93924  0.930110  16.237859
16   구로구  4608   2.184332  419984  396017  23967  73864  5.706646  17.587337
17   금천구  2411   1.528610  244901  231098  13803  41819  5.636155  17.075880
18  영등포구  4056  23.015385  400241  376740  23501  63547  5.871712  15.877184
19   동작구  2306   1.363354  394649  386017   8632  67470  2.187260  17.096204
20   관악구  5149   0.952941  500336  486375  13961  80686  2.790325  16.126363
21   서초구  4082   2.917404  413677  409823   3854  61404  0.931645  14.843465
22   강남구  6871   1.823009  537338  532577   4761  79575  0.886034  14.809115
23   송파구  2897   0.352283  668261  662607   5654  99854  0.846077  14.942365
24   강동구  2809   2.460674  465097  461300   3797  75477  0.816389  16.228228

* 12번 : data_result 인덱스를 구별로 설정

In [40]:
data_result.set_index('구별', inplace=True)

In [41]:
data_result

        총계      최근증가율     인구수     한국인    외국인    고령자     외국인비율      고령자비율
구별
종로구   1715  22.222222  153684  144275   9409  28064  6.122303  18.260847
중구    2447   4.929032  131450  122173   9277  24742  7.057436  18.822366
용산구   2611   2.752443  236518  222169  14349  39461  6.066769  16.684142
성동구   3829   1.540816  291609  285073   6536  46896  2.241357  16.081808
광진구   3211   1.165730  353110  340707  12403  52604  3.512503  14.897341
동대문구  2628   2.027523  352592  337982  14610  62963  4.143599  17.857183
중랑구   3737   1.317445  393600  389043   4557  72851  1.157774  18.508892
성북구   4602   0.920168  442680  433150   9530  75719  2.152797  17.104681
강북구   3090   1.044527  300824  297384   3440  64961  1.143526  21.594354
도봉구   1930   3.700000  318100  316098   2002  65122  0.629362  20.472179
노원구   2492   1.900000  514445  510486   3959  89426  0.769567  17.383005
은평구   4131   0.718070  476013  472259   3754  88418  0.788634  18.574703
서대문구  3055   1.495627  317075  305866  11209  55012  3.535126  17.349838
마포구   2496   0.823887  378629  368331  10298  55168  2.719813  14.570463
양천구   3650   2.298077  449378  446182   3196  69953  0.711205  15.566628
강서구   2744   1.472648  578426  573046   5380  93924  0.930110  16.237859
구로구   4608   2.184332  419984  396017  23967  73864  5.706646  17.587337
금천구   2411   1.528610  244901  231098  13803  41819  5.636155  17.075880
영등포구  4056  23.015385  400241  376740  23501  63547  5.871712  15.877184
동작구   2306   1.363354  394649  386017   8632  67470  2.187260  17.096204
관악구   5149   0.952941  500336  486375  13961  80686  2.790325  16.126363
서초구   4082   2.917404  413677  409823   3854  61404  0.931645  14.843465
강남구   6871   1.823009  537338  532577   4761  79575  0.886034  14.809115
송파구   2897   0.352283  668261  662607   5654  99854  0.846077  14.942365
강동구   2809   2.460674  465097  461300   3797  75477  0.816389  16.228228

## 상관관계 분석

-1 ~ 0 ~ 1(절대값)  
0.1 이하 : 관계없음. 무시  
0.3 이하 : 약한 상관 관계  
0.7 이하 : 뚜렷한 상관 관계

### 고령자 비율, cctv 총계 상관관계

In [42]:
np.corrcoef(data_result['고령자비율'], data_result['총계'])  #음수면 앞의거 적을수록 뒤에거가 크다는뜻

array([[ 1.        , -0.33822133],
       [-0.33822133,  1.        ]])

### 외국인비율, cctv 총계 상관관계

In [43]:
np.corrcoef(data_result['외국인비율'], data_result['총계'])

array([[ 1.        , -0.21514858],
       [-0.21514858,  1.        ]])

### 인구수, cctv 총계 상관관계

In [44]:
np.corrcoef(data_result['인구수'], data_result['총계'])

array([[1.        , 0.44406377],
       [0.44406377, 1.        ]])

In [45]:
data_result.to_csv('data_result.csv')

In [46]:
cctv.to_csv('cctv.csv')

In [47]:
pop.to_csv('pop.csv')